**Import Libraries**

In [1]:
import warnings
import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:.2f}".format)

**Load Dataset**

In [2]:
from google.colab import files
uploaded = files.upload()

Saving superstore_raw.csv to superstore_raw.csv

In [3]:
df = pd.read_csv(
    "/content/superstore_raw.csv",
    encoding="latin1"
)

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.00,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.00,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,Califronia,90036.00,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.00,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.58,5,0.45,-383.03
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.00,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52

**Dataset Overview**

In [4]:
print("=" * 50)
print("DATASET OVERVIEW")
print("=" * 50)

print(f"Rows    : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]}")

==================================================
DATASET OVERVIEW
==================================================
Rows    : 10,114
Columns : 21

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10114 entries, 0 to 10113
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         10114 non-null  int64
 1   Order ID       10114 non-null  object
 2   Order Date     10114 non-null  object
 3   Ship Date      10114 non-null  object
 4   Ship Mode      10114 non-null  object
 5   Customer ID    10114 non-null  object
 6   Customer Name  9861 non-null   object
 7   Segment        10114 non-null  object
 8   Country        10114 non-null  object
 9   City           10032 non-null  object
 10  State          10114 non-null  object
 11  Postal Code    9864 non-null   float64
 12  Region         9864 non-null   object
 13  Product ID     10114 non-null  object
 14  Category       10114 non-null  object
 15  Sub-Category   10114 non-null  object
 16  Product Name   9859 non-null   object
 17  Sales          10114 non-null  float64
 18  Quantity       10114 non-null  int64
 19  Discount       10114 non-null  float64
 20  Profit         10114 non-null  float64
dtypes: float64(4), int64(2), object(15)
memory usage: 1.6+ MB

In [6]:
df.describe()

        Row ID  Postal Code     Sales  Quantity  Discount   Profit
count 10114.00      9864.00  10114.00  10114.00  10114.00 10114.00
mean   4993.36     55135.57   1217.45      3.78      0.16    29.89
std    2885.21     32036.25  31428.91      2.23      0.21   236.88
min       1.00      1040.00  -1036.62      0.00      0.00 -6599.98
25%    2495.25     23223.00     17.14      2.00      0.00     1.74
50%    4987.50     55901.00     54.51      3.00      0.20     8.69
75%    7489.75     90005.00    209.98      5.00      0.20    29.51
max    9994.00     99301.00 999999.00     14.00      1.25  8399.98

In [7]:
df.describe(include="object")

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name
count,10114,10114,10114,10114,10114,9861,10114,10114,10032,10114,9864,10114,10114,10114,9859
unique,5009,1500,1600,4,793,840,11,1,531,79,4,1862,9,17,1849
top,CA-2017-100111,9/5/2016,12/16/2015,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,Califronia,West,OFF-PA-10001970,Office Supplies,Binders,Staple envelope
freq,14,37,35,6029,38,37,5095,10114,921,1994,3143,19,5950,1537,48

In [8]:
df.sample(5, random_state=42)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
7407,7408,CA-2017-152079,1/20/2017,1/21/2017,First Class,ML-17410,Maris LaWare,Consumer,United States,Chicago,Illinois,60653.00,Central,OFF-LA-10001613,Office Supplies,Labels,Avery File Folder Labels,11.52,5,0.20,4.18
7905,7906,US-2015-118766,10/15/2015,10/22/2015,Standard Class,LS-16975,Lindsay Shagiari,Home Office,United States,Dallas,Texsas,75217.00,Central,OFF-EN-10001415,Office Supplies,Envelopes,Staple envelope,4.46,1,0.20,1.67
4901,4902,CA-2017-120936,12/17/2017,12/21/2017,Standard Class,CA-12310,Christine Abelman,Corporate,United States,Anaheim,Califronia,92804.00,West,OFF-SU-10002557,Office Supplies,Supplies,Fiskars Spring-Action Scissors,13.98,1,0.00,3.63
2986,2987,CA-2016-139269,5/25/2016,5/30/2016,Standard Class,JB-16045,Julia Barnett,Home Office,United States,Columbus,Georgia,31907.00,South,OFF-PA-10002893,Office Supplies,Paper,"Wirebound Service Call Books, 5 1/2"" x 4""",19.36,2,0.00,9.29
4955,4956,CA-2014-160262,6/9/2014,6/13/2014,Second Class,TS-21205,Thomas Seio,Corporate,United States,North Las Vegas,Nevada,89031.00,West,OFF-PA-10003641,Office Supplies,Paper,Xerox 1909,79.14,3,0.00,36.40

**Data Quality Assessment**

In [9]:
missing_summary = (
    df.isna()
      .sum()
      .to_frame("Missing Values")
)

missing_summary["Percentage"] = (
    missing_summary["Missing Values"]
    / len(df)
    * 100
).round(2)

missing_summary.sort_values(
    by="Missing Values",
    ascending=False
)

               Missing Values  Percentage
Product Name              255        2.52
Customer Name             253        2.50
Postal Code               250        2.47
Region                    250        2.47
City                       82        0.81
Ship Mode                   0        0.00
Ship Date                   0        0.00
Order Date                  0        0.00
Order ID                    0        0.00
Row ID                      0        0.00
Country                     0        0.00
Customer ID                 0        0.00
Segment                     0        0.00
State                       0        0.00
Product ID                  0        0.00
Category                    0        0.00
Sub-Category                0        0.00
Sales                       0        0.00
Quantity                    0        0.00
Discount                    0        0.00
Profit                      0        0.00

In [10]:
duplicate_count = df.duplicated().sum()
print(f"Duplicate Records : {duplicate_count}")

Duplicate Records : 120

In [11]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code      float64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [12]:
empty_string = (
    df.select_dtypes(include="object")
      .apply(lambda x: (x.str.strip() == "").sum())
      .to_frame("Empty String")
)

empty_string

               Empty String
Order ID                  0
Order Date                0
Ship Date                 0
Ship Mode                 0
Customer ID               0
Customer Name             0
Segment                   0
Country                   0
City                      0
State                     0
Region                    0
Product ID                0
Category                  0
Sub-Category              0
Product Name              0

In [13]:
df.nunique().sort_values()

Country             1
Ship Mode           4
Region              4
Category            9
Segment            11
Discount           13
Quantity           15
Sub-Category       17
State              79
City              531
Postal Code       630
Customer ID       793
Customer Name     840
Order Date       1500
Ship Date        1600
Product Name     1849
Product ID       1862
Order ID         5009
Sales            5835
Profit           7293
Row ID           9994
dtype: int64

**Data Cleaning**

In [14]:
text_columns = df.select_dtypes(include="object").columns

df[text_columns] = df[text_columns].apply(
    lambda x: x.str.strip()
)

In [15]:
df["Category"] = df["Category"].str.title()

In [16]:
df["Segment"] = df["Segment"].str.title()

In [17]:
df["State"] = df["State"].str.title()

In [18]:
state_mapping = {
    "Califronia": "California",
    "Texsas": "Texas",
    "Newyork": "New York"
}

df["State"] = df["State"].replace(state_mapping)

In [19]:
df.replace(
    "",
    np.nan,
    inplace=True
)

In [20]:
date_columns = [
    "Order Date",
    "Ship Date"
]

for column in date_columns:

    df[column] = pd.to_datetime(
        df[column],
        format="mixed",
        errors="coerce"
    )

In [21]:
df[date_columns].isna().sum()

Order Date    0
Ship Date     0
dtype: int64

In [22]:
df.dropna(
    subset=date_columns,
    inplace=True
)

In [23]:
df.drop_duplicates(
    inplace=True
)

df.reset_index(
    drop=True,
    inplace=True
)

In [24]:
df["Customer Name"] = (
    df["Customer Name"]
      .fillna("Unknown Customer")
)

In [25]:
df["Postal Code"] = (
    df["Postal Code"]
      .fillna(0)
      .astype(int)
)

In [26]:
mode_region = df["Region"].mode()[0]

df["Region"] = (
    df["Region"]
      .fillna(mode_region)
)

In [27]:
df["Product Name"] = (
    df["Product Name"]
      .fillna("Unknown Product")
)

In [28]:
df = df[df["Sales"] > 0]

In [29]:
df = df[df["Quantity"] > 0]

In [30]:
df.loc[
    df["Discount"] > 1,
    "Discount"
] = 1

In [31]:
df = df[
    df["Profit"] <= df["Sales"] * 2
]

In [32]:
Q1 = df["Sales"].quantile(.25)
Q3 = df["Sales"].quantile(.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df = df[
    (df["Sales"] >= lower) &
    (df["Sales"] <= upper)
]

**Feature Engineering**

In [33]:
df["Order Year"] = df["Order Date"].dt.year

df["Order Quarter"] = df["Order Date"].dt.quarter

df["Order Month"] = df["Order Date"].dt.month

df["Order Month Name"] = df["Order Date"].dt.month_name()

df["Order Weekday"] = df["Order Date"].dt.day_name()

df["Shipping Days"] = (
    df["Ship Date"] -
    df["Order Date"]
).dt.days

df["Profit Margin (%)"] = np.where(
    df["Sales"] != 0,
    (df["Profit"] / df["Sales"]) * 100,
    0
).round(2)

df["Sales per Unit"] = (
    df["Sales"] /
    df["Quantity"]
).round(2)

df["Profit per Unit"] = (
    df["Profit"] /
    df["Quantity"]
).round(2)

**Final Validation**

In [34]:
print("="*50)
print("FINAL DATA VALIDATION")
print("="*50)

print(f"Rows              : {df.shape[0]:,}")
print(f"Columns           : {df.shape[1]}")
print(f"Missing Values    : {df.isna().sum().sum()}")
print(f"Duplicate Records : {df.duplicated().sum()}")

==================================================
FINAL DATA VALIDATION
==================================================
Rows              : 8,775
Columns           : 30
Missing Values    : 66
Duplicate Records : 0

In [35]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order Year,Order Quarter,Order Month,Order Month Name,Order Weekday,Shipping Days,Profit Margin (%),Sales per Unit,Profit per Unit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91,2016,4,11,November,Tuesday,3,16.00,130.98,20.96
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87,2016,2,6,June,Sunday,4,47.00,7.31,3.44
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52,2015,4,10,October,Sunday,7,11.25,11.18,1.26
5,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.86,7,0.00,14.17,2014,2,6,June,Monday,5,29.00,6.98,2.02
6,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.28,4,0.00,1.97,2014,2,6,June,Monday,5,27.00,1.82,0.49

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8775 entries, 0 to 9993
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Row ID             8775 non-null   int64
 1   Order ID           8775 non-null   object
 2   Order Date         8775 non-null   datetime64[ns]
 3   Ship Date          8775 non-null   datetime64[ns]
 4   Ship Mode          8775 non-null   object
 5   Customer ID        8775 non-null   object
 6   Customer Name      8775 non-null   object
 7   Segment            8775 non-null   object
 8   Country            8775 non-null   object
 9   City               8709 non-null   object
 10  State              8775 non-null   object
 11  Postal Code        8775 non-null   int64
 12  Region             8775 non-null   object
 13  Product ID         8775 non-null   object
 14  Category           8775 non-null   object
 15  Sub-Category       8775 non-null   object
 16  Product Name       8775 non-null   object
 17  Sales              8775 non-null   float64
 18  Quantity           8775 non-null   int64
 19  Discount           8775 non-null   float64
 20  Profit             8775 non-null   float64
 21  Order Year         8775 non-null   int32
 22  Order Quarter      8775 non-null   int32
 23  Order Month        8775 non-null   int32
 24  Order Month Name   8775 non-null   object
 25  Order Weekday      8775 non-null   object
 26  Shipping Days      8775 non-null   int64
 27  Profit Margin (%)  8775 non-null   float64
 28  Sales per Unit     8775 non-null   float64
 29  Profit per Unit    8775 non-null   float64
dtypes: datetime64[ns](2), float64(6), int32(3), int64(4), object(15)
memory usage: 2.0+ MB

**Export Clean Dataset**

In [37]:
OUTPUT_FILE = "superstore_clean.csv"

df.to_csv(
    OUTPUT_FILE,
    index=False
)

print(f"Dataset exported successfully: {OUTPUT_FILE}")

Dataset exported successfully: superstore_clean.csv

In [38]:
from google.colab import files

files.download(OUTPUT_FILE)